PYTHON = python
PYTHONPATH = ~/projects

all:	compile install

compile:
	cd mxQueue; \
	if ! test -f Makefile; then $(MAKE) -f Makefile.pre.in boot; fi; \
	$(MAKE)

install:
	cd mxQueue; \
	$(MAKE) install

test:
	cd mxQueue; \
	export PYTHONPATH=$(PYTHONPATH); \
	$(PYTHON) test.py

doc:
	-true


# Cleanup before distributing the package
#
distclean:
	cd mxQueue; \
	$(MAKE) distclean
